POST https://localhost:5001/api/Utilisateur/Register
Content-Type: application/json

{
  "name": "joffrey",
  "email": "lemery.joffrey@outlook.fr",
  "password": "Test123a!"

}

###

POST https://localhost:5001/api/Utilisateur/Login
Content-Type: application/json

{
"name": "joffrey",
"email": "lemery.joffrey@outlook.fr",
"password": "Test123a!"

}

###

GET https://localhost:5001/api/Utilisateur/GetId/?email=lemery.joffrey@outlook.fr
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjIiLCJlbWFpbCI6ImxlbWVyeS5qb2ZmcmV5QG91dGxvb2suZnIiLCJzdWIiOiJsZW1lcnkuam9mZnJleUBvdXRsb29rLmZyIiwianRpIjoiMDM3N2EzZTYtZTQyYS00MmExLTlmMzYtZDNhNWU5NmIyYTI4IiwibmJmIjoxNjM1NTI2NTE2LCJleHAiOjE2MzU1MzAxMTYsImlhdCI6MTYzNTUyNjUxNn0.6nl1acCGFj5Bzg5GoVIic6bt9iwKzOmo3Ktlgmer1T0

###

PUT https://localhost:5001/api/Utilisateur/Update/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjIiLCJlbWFpbCI6ImxlbWVyeS5qb2ZmcmV5QG91dGxvb2suZnIiLCJzdWIiOiJsZW1lcnkuam9mZnJleUBvdXRsb29rLmZyIiwianRpIjoiMDM3N2EzZTYtZTQyYS00MmExLTlmMzYtZDNhNWU5NmIyYTI4IiwibmJmIjoxNjM1NTI2NTE2LCJleHAiOjE2MzU1MzAxMTYsImlhdCI6MTYzNTUyNjUxNn0.6nl1acCGFj5Bzg5GoVIic6bt9iwKzOmo3Ktlgmer1T0

{  
"name": "joffrey2",
"email": "lemery.joffrey@outlook.fr2",
"password": "Test123a!1"
}

###

DELETE https://localhost:5001/api/Utilisateur/Delete
